import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, ButtonToolbar } from 'rsuite';
import FacebookOfficialIcon from '@rsuite/icons/legacy/FacebookOfficial';
import { useRouter } from 'next/router';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" style={{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        padding:10,
        width:"100vw",
        height:"100vh",
        gap:10
      }}>
      <Button color="blue" appearance="primary" onClick={()=>router.push("/Student")} startIcon={<FacebookOfficialIcon />}>
        student
      </Button>
      <Button color="blue" appearance="primary" onClick={()=>router.push("/Teacher")} startIcon={<FacebookOfficialIcon />}>
        teacher
      </Button>
      </div>
    </>
  )
}
